<?php

namespace AppBundle\Repository;

/**
 * DocentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocentRepository extends \Doctrine\ORM\EntityRepository
{
}
