<?php

namespace AppBundle\Repository;

/**
 * ProeflesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProeflesRepository extends \Doctrine\ORM\EntityRepository
{
}
