<?php

namespace AppBundle\Repository;

/**
 * ProeflessenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProeflessenRepository extends \Doctrine\ORM\EntityRepository
{
}
